import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#d9e3f3",
        "on-secondary": "#00363d",
        "on-surface": "#d5e3ff",
        "tertiary-container": "#8892a0",
        "surface-dim": "#041428",
        "surface-container-highest": "#27354c",
        "secondary-fixed-dim": "#00daf3",
        "surface-tint": "#a5c8ff",
        "on-primary": "#00315f",
        "on-primary-container": "#002a53",
        "on-secondary-fixed": "#001f24",
        "surface-variant": "#27354c",
        "surface-container-lowest": "#000e23",
        "on-secondary-container": "#00616d",
        "outline-variant": "#404753",
        "primary": "#a5c8ff",
        "secondary-fixed": "#9cf0ff",
        "inverse-on-surface": "#223147",
        "on-tertiary-fixed": "#131c27",
        "outline": "#8a919f",
        "background": "#041428",
        "on-tertiary": "#27313d",
        "surface-container-low": "#0c1c31",
        "secondary": "#bdf4ff",
        "on-surface-variant": "#c0c7d6",
        "secondary-container": "#00e3fd",
        "surface-container": "#112035",
        "surface": "#041428",
        "on-tertiary-container": "#212a36",
        "primary-fixed-dim": "#a5c8ff",
        "on-secondary-fixed-variant": "#004f58",
        "primary-fixed": "#d4e3ff",
        "tertiary-fixed-dim": "#bdc7d6",
        "on-error": "#690005",
        "surface-bright": "#2b3a50",
        "inverse-primary": "#005faf",
        "on-error-container": "#ffdad6",
        "on-tertiary-fixed-variant": "#3e4854",
        "primary-container": "#2792ff",
        "error-container": "#93000a",
        "on-background": "#d5e3ff",
        "on-primary-fixed": "#001c3a",
        "on-primary-fixed-variant": "#004786",
        "surface-container-high": "#1c2a40",
        "inverse-surface": "#d5e3ff",
        "tertiary": "#bdc7d6",
        "error": "#ffb4ab",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      fontFamily: {
        headline: ["var(--font-headline)"],
        body: ["var(--font-body)"],
        label: ["var(--font-label)"],
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};

export default config;
