import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container": "#f0eded",
        "on-primary-container": "#778598",
        "secondary-fixed-dim": "#e9c176",
        "on-tertiary": "#ffffff",
        "surface-container-high": "#eae7e7",
        "outline": "#74777d",
        "inverse-surface": "#313030",
        "surface-dim": "#dcd9d9",
        "on-secondary-container": "#785a1a",
        "secondary-fixed": "#ffdea5",
        "on-surface": "#1c1b1b",
        "inverse-on-surface": "#f3f0ef",
        "on-tertiary-fixed-variant": "#584329",
        "surface-container-highest": "#e5e2e1",
        "tertiary-fixed-dim": "#e0c1a0",
        "tertiary": "#000000",
        "tertiary-fixed": "#feddba",
        "on-secondary-fixed": "#261900",
        "on-error-container": "#93000a",
        "surface-bright": "#fcf9f8",
        "surface": "#fcf9f8",
        "inverse-primary": "#bac8dc",
        "error-container": "#ffdad6",
        "on-background": "#1c1b1b",
        "on-tertiary-fixed": "#281804",
        "secondary": "#775a19",
        "on-primary-fixed-variant": "#3a4859",
        "surface-variant": "#e5e2e1",
        "on-surface-variant": "#44474c",
        "on-primary-fixed": "#0f1c2c",
        "tertiary-container": "#281804",
        "background": "#fcf9f8",
        "primary-container": "#0f1c2c",
        "on-primary": "#ffffff",
        "primary": "#000000",
        "error": "#ba1a1a",
        "surface-container-low": "#f6f3f2",
        "on-tertiary-container": "#9a7f61",
        "on-secondary-fixed-variant": "#5d4201",
        "outline-variant": "#c4c6cc",
        "primary-fixed-dim": "#bac8dc",
        "surface-tint": "#525f71",
        "primary-fixed": "#d6e4f9",
        "surface-container-lowest": "#ffffff",
        "on-secondary": "#ffffff",
        "on-error": "#ffffff",
        "secondary-container": "#fed488",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      fontFamily: {
        headline: ["Noto Serif", "serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};

export default config;
